"""empty message

Revision ID: 7c715b9777ad
Revises: f89c2a2df5fc
Create Date: 2022-05-30 17:37:35.741855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c715b9777ad'
down_revision = 'f89c2a2df5fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genre')
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    op.drop_column('Venue', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genre', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'genres')
    op.add_column('Artist', sa.Column('genre', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
